import { MarketplaceLayout } from "@/components/MarketplaceLayout";
import { trpc } from "@/lib/trpc";
import { ShieldCheck } from "lucide-react";
import { toast } from "sonner";

export default function Admin() {
  const pending = trpc.marketplace.v3PendingProducts.useQuery();
  const moderate = trpc.marketplace.moderateV3Product.useMutation({ onSuccess: () => { toast.success("Product moderation recorded."); pending.refetch(); }, onError: error => toast.error(error.message) });
  return <MarketplaceLayout><main className="mx-auto max-w-5xl px-5 py-14"><p className="eyebrow">Owner operations</p><h1 className="mt-2 text-4xl font-semibold">Product moderation</h1><p className="mt-3 max-w-2xl text-muted-foreground">Only the verified MtaaMarket owner role can review pending V3 listings. Approval makes a listing available to the public catalogue.</p>{pending.isError ? <div className="mt-8 rounded-xl border p-5"><ShieldCheck className="mb-3" /><strong>Owner access required</strong><p className="mt-2 text-sm text-muted-foreground">Sign in with the verified owner email session to review listings.</p></div> : <div className="mt-8 grid gap-4 sm:grid-cols-2">{pending.data?.map(product => <article className="rounded-xl border bg-white p-5" key={product.id}><img className="h-40 w-full rounded-lg object-cover" src={product.image_url} alt="" /><h2 className="mt-4 font-semibold">{product.title}</h2><p className="mt-1 text-sm text-muted-foreground">Vendor ID: {product.vendor_id || "Owner listing"}</p><p className="mt-1 font-medium">KES {Number(product.final_price).toLocaleString("en-KE")}</p><div className="mt-4 flex gap-2"><button className="primary-cta" onClick={() => moderate.mutate({ productId: product.id, status: "ACTIVE" })}>Approve</button><button className="secondary-cta" onClick={() => moderate.mutate({ productId: product.id, status: "REJECTED" })}>Reject</button></div></article>) || <p className="text-muted-foreground">Loading pending listings…</p>}{pending.data?.length === 0 && <p className="text-muted-foreground">No pending products to review.</p>}</div>}</main></MarketplaceLayout>;
}
