import { MarketplaceLayout } from "@/components/MarketplaceLayout";
import { useSupabaseAuth } from "@/contexts/SupabaseAuthContext";
import { trpc } from "@/lib/trpc";
import { ArrowRight, ClipboardList, LockKeyhole, ShieldCheck, ShoppingBag, Store } from "lucide-react";
import { Link } from "wouter";

export default function DashboardPage() {
  const { configured, loading, session } = useSupabaseAuth();
  const vendorAccess = trpc.marketplace.v3VendorAccess.useQuery(undefined, { enabled: Boolean(session), retry: false });

  return <MarketplaceLayout>
    {!configured && <section className="auth-gate"><LockKeyhole aria-hidden="true" /><p className="eyebrow">MtaaMarket account</p><h1>Account access is being prepared.</h1><p>Email sign-in is not configured in this environment yet. Return to the market after account access has been configured.</p><Link href="/" className="secondary-cta mt-6">Return to market <ArrowRight size={17} /></Link></section>}
    {configured && loading && <section className="auth-gate" aria-live="polite"><LockKeyhole aria-hidden="true" /><p className="eyebrow">Private MtaaMarket workspace</p><h1>Checking your account session.</h1><p>Your account-linked workspace will appear after the secure session check completes.</p></section>}
    {configured && !loading && !session && <section className="auth-gate"><LockKeyhole aria-hidden="true" /><p className="eyebrow">Private MtaaMarket workspace</p><h1>Sign in to open your workspace.</h1><p>Use the Account button in the header. The same verified MtaaMarket account can browse, request items, use Seller Studio when eligible, and access the owner console when it has the founder owner role.</p><Link href="/" className="primary-cta mt-6">Return to market and sign in <ArrowRight size={17} /></Link></section>}
    {configured && !loading && session && <section className="mx-auto max-w-5xl px-5 py-14"><p className="eyebrow">One account, protected workspaces</p><h1 className="mt-2 text-4xl font-semibold">Your MtaaMarket workspace</h1><p className="mt-3 max-w-2xl text-muted-foreground">Use the same verified founder account across buyer requests, Seller Studio, owner moderation, and fulfilment. Public products remain hidden until owner review changes their status.</p>{vendorAccess.isError && <p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950" role="status">Your account is signed in, but workspace permissions could not be checked. Refresh before opening a protected action.</p>}<div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Link href="/cart" className="rounded-2xl border bg-white p-5 transition hover:-translate-y-0.5"><ShoppingBag size={20} /><h2 className="mt-4 font-semibold">Your basket</h2><p className="mt-2 text-sm text-muted-foreground">Review products and protected collection options.</p></Link><Link href="/request" className="rounded-2xl border bg-white p-5 transition hover:-translate-y-0.5"><ClipboardList size={20} /><h2 className="mt-4 font-semibold">Request Desk</h2><p className="mt-2 text-sm text-muted-foreground">Submit a custom item request for owner review.</p></Link><Link href="/vendor/upload" className="rounded-2xl border bg-white p-5 transition hover:-translate-y-0.5"><Store size={20} /><h2 className="mt-4 font-semibold">Seller Studio</h2><p className="mt-2 text-sm text-muted-foreground">Founders can submit owner listings directly; ordinary vendors need approval.</p></Link><Link href="/admin" className="rounded-2xl border bg-white p-5 transition hover:-translate-y-0.5"><ShieldCheck size={20} /><h2 className="mt-4 font-semibold">Owner console</h2><p className="mt-2 text-sm text-muted-foreground">Review pending listings, requests, vendor applications, and fulfilment records.</p></Link></div></section>}
  </MarketplaceLayout>;
}
