import { MarketplaceLayout } from "@/components/MarketplaceLayout";
import { formatKes } from "@/components/ProductCard";
import { VendorProductForm } from "@/components/VendorProductForm";
import { AdminOperationsPanel } from "@/components/AdminOperationsPanel";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { Bell, CheckCircle2, CircleAlert, ClipboardPlus, Clock3, LayoutDashboard, PackageCheck, PackageOpen, Plus, ShieldAlert, Store, WalletCards, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

function OrderStatus({ status }: { status: string }) {
  const labels: Record<string, string> = { pending_payment: "Awaiting payment", paid_escrow: "Paid · held in escrow", ready_for_pickup: "Ready for pickup", picked_up: "Pickup confirmed", released_vendor: "Completed", disputed: "Dispute open", cancelled: "Cancelled" };
  return <span className={`order-status ${status}`}>{labels[status] || status}</span>;
}

function BecomeVendor({ onReady }: { onReady: () => void }) {
  const mutation = trpc.marketplace.becomeVendor.useMutation({ onSuccess: () => { toast.success("Your seller workspace is ready."); onReady(); }, onError: error => toast.error(error.message) });
  const [storeName, setStoreName] = useState(""); const [storeSlug, setStoreSlug] = useState(""); const [description, setDescription] = useState(""); const [serviceArea, setServiceArea] = useState("Serves Siaya County");
  const submit = (event: FormEvent) => { event.preventDefault(); mutation.mutate({ storeName, storeSlug, description: description || undefined, serviceArea }); };
  return <form onSubmit={submit} className="onboarding-card"><div><p className="eyebrow">Apply to Seller Studio</p><h2>Set up your seller application</h2><p>MtaaMarket reviews every seller first. Once approved, you can publish physical-product listings immediately for Siaya buyers.</p></div><div className="form-grid"><label>Store name<input value={storeName} onChange={event => { setStoreName(event.target.value); setStoreSlug(event.target.value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")); }} required minLength={3} /></label><label>Store link<input value={storeSlug} onChange={event => setStoreSlug(event.target.value)} required pattern="[a-z0-9-]+" /></label><label className="full-span">How you serve Siaya<input value={serviceArea} onChange={event => setServiceArea(event.target.value)} required maxLength={240} placeholder="e.g. Delivers to Siaya Town and Bondo" /></label><label className="full-span">About your store<textarea value={description} onChange={event => setDescription(event.target.value)} maxLength={1500} placeholder="Tell MtaaMarket what physical products you sell." /></label></div><button className="primary-cta" disabled={mutation.isPending}>{mutation.isPending ? "Submitting…" : "Submit seller application"}<Store size={17} /></button></form>;
}

export default function DashboardPage() {
  const { isAuthenticated, loading } = useAuth();
  const profile = trpc.marketplace.myProfile.useQuery(undefined, { enabled: isAuthenticated });
  const buyerOrders = trpc.marketplace.buyerOrders.useQuery(undefined, { enabled: isAuthenticated });
  const buyerRequests = trpc.marketplace.buyerItemRequests.useQuery(undefined, { enabled: isAuthenticated });
  const notifications = trpc.marketplace.notifications.useQuery(undefined, { enabled: isAuthenticated });
  const vendorDashboard = trpc.marketplace.vendorDashboard.useQuery(undefined, { enabled: profile.data?.role === "vendor" || profile.data?.role === "admin" });
  const adminSummary = trpc.marketplace.adminSummary.useQuery(undefined, { enabled: profile.data?.role === "admin" });
  const [disputeOrderId, setDisputeOrderId] = useState<number | null>(null);
  const [disputeReason, setDisputeReason] = useState("");
  const [disputeDetails, setDisputeDetails] = useState("");
  const confirmPickup = trpc.marketplace.confirmPickup.useMutation({ onSuccess: () => { toast.success("Pickup confirmation recorded. The dispute window is now open."); buyerOrders.refetch(); notifications.refetch(); }, onError: error => toast.error(error.message) });
  const openDispute = trpc.marketplace.openDispute.useMutation({ onSuccess: () => { toast.success("Your dispute is open. Escrow remains held while it is reviewed."); setDisputeOrderId(null); setDisputeReason(""); setDisputeDetails(""); buyerOrders.refetch(); notifications.refetch(); }, onError: error => toast.error(error.message) });

  if (loading) return <MarketplaceLayout><div className="page-loading">Opening your workspace…</div></MarketplaceLayout>;
  if (!isAuthenticated) return <MarketplaceLayout><div className="auth-gate"><WalletCards /><p className="eyebrow">Your marketplace workspace</p><h1>Sign in to manage orders and listings.</h1><p>Keep your pickup details, payment updates, notifications, and seller tools in one place.</p><button className="primary-cta" onClick={startLogin}>Sign in to continue</button></div></MarketplaceLayout>;

  const isVendor = profile.data?.role === "vendor" || profile.data?.role === "admin";
  const submitDispute = (event: FormEvent) => { event.preventDefault(); if (disputeOrderId) openDispute.mutate({ orderId: disputeOrderId, reason: disputeReason, details: disputeDetails }); };
  return <MarketplaceLayout><div className="dashboard-page">
    <div className="dashboard-intro"><div><p className="eyebrow">MtaaMarket workspace</p><h1>Welcome back, {profile.data?.displayName?.split(" ")[0] || "shopper"}.</h1><p>Follow your order and Request Desk updates in one private place. MtaaMarket confirms each fulfilment and payment step before it happens.</p></div><Link href="/" className="secondary-cta">Browse market <PackageOpen size={17} /></Link></div>
    <div className="dashboard-tabs"><a href="#orders"><PackageOpen size={16} /> Orders</a><a href="#requests"><ClipboardPlus size={16} /> Requests</a><a href="#notifications"><Bell size={16} /> Updates</a><a href="#seller"><Store size={16} /> Seller Studio</a>{profile.data?.role === "admin" && <a href="#operations"><ShieldAlert size={16} /> Operations</a>}</div>
    <div className="dashboard-grid">
      <section id="orders" className="workspace-card orders-workspace"><div className="card-title"><div><p className="eyebrow">Buyer workspace</p><h2>Your orders</h2></div><PackageCheck /></div>{buyerOrders.isLoading ? <p className="muted-copy">Loading your order history…</p> : buyerOrders.data?.length ? <div className="order-list">{buyerOrders.data.map(({ order, station, vendor }) => <article className="order-row" key={order.id}><div><OrderStatus status={order.status} /><h3>{order.orderNumber}</h3><p>{station?.name || order.fulfilmentMethod.replaceAll("_", " ")}{vendor?.storeName ? ` · ${vendor.storeName}` : ""}</p></div><div><strong>{formatKes(order.totalAmount)}</strong><span>{new Date(order.createdAt).toLocaleDateString("en-KE")}</span></div><div className="order-actions">{order.status === "ready_for_pickup" && <button onClick={() => confirmPickup.mutate({ orderId: order.id })} className="small-cta">Confirm fulfilment</button>}{["paid_escrow", "ready_for_pickup", "picked_up"].includes(order.status) && <button onClick={() => setDisputeOrderId(order.id)} className="small-cta dispute-action"><CircleAlert size={13} /> Open dispute</button>}</div></article>)}</div> : <div className="workspace-empty"><PackageOpen /><h3>No marketplace orders yet.</h3><p>Send an order request when you are ready; MtaaMarket will confirm the next step privately.</p><Link href="/request" className="text-cta">Open Request Desk</Link></div>}</section>
      <aside id="notifications" className="workspace-card notification-workspace"><div className="card-title"><div><p className="eyebrow">Order updates</p><h2>Notifications</h2></div><Bell /></div>{notifications.data?.length ? <div className="notification-list">{notifications.data.slice(0, 5).map(notification => <div className={notification.isRead ? "notification" : "notification unread"} key={notification.id}><span className={`notification-dot ${notification.type}`} /><div><strong>{notification.title}</strong><p>{notification.body}</p></div></div>)}</div> : <div className="workspace-empty compact"><Bell /><p>Important payment, pickup, delivery, and dispute updates will be shown here.</p></div>}</aside>
    </div>
    <section id="requests" className="workspace-card request-history"><div className="card-title"><div><p className="eyebrow">Request Desk</p><h2>Your item requests</h2></div><ClipboardPlus /></div>{buyerRequests.isLoading ? <p className="muted-copy">Loading your requests…</p> : buyerRequests.data?.length ? <div className="inventory-list">{buyerRequests.data.map(request => <div key={request.id}><span className={`listing-status ${request.status}`}>{request.status.replaceAll("_", " ")}</span><strong>{request.title}</strong><p>{request.platformReply || "MtaaMarket will update you after reviewing a real available route."}</p></div>)}</div> : <div className="workspace-empty compact"><ClipboardPlus /><p>Use the Request Desk when the product you need is not listed yet.</p><Link href="/request" className="text-cta">Send an item request</Link></div>}</section>
      <section id="seller" className="seller-workspace">{profile.data?.role === "buyer" ? <BecomeVendor onReady={() => profile.refetch()} /> : isVendor ? <><div className="vendor-workspace-header"><div><p className="eyebrow">Seller Studio</p><h2>{vendorDashboard.data?.vendor?.storeName || "Your seller tools"}</h2><p>{vendorDashboard.data?.vendor?.approvalStatus === "approved" ? "Your approved listings can go live immediately. MtaaMarket keeps buyer communication private." : "Your Seller Studio is waiting for MtaaMarket approval. You will be able to list once approved."}</p></div><span className="verification-badge">{vendorDashboard.data?.vendor?.approvalStatus === "approved" ? <><CheckCircle2 size={15} /> Approved seller</> : <><Clock3 size={15} /> Approval pending</>}</span></div><div className="seller-grid">{vendorDashboard.data?.vendor?.approvalStatus === "approved" ? <VendorProductForm onCreated={() => vendorDashboard.refetch()} /> : <div className="workspace-card seller-orders"><Clock3 /><h3>Seller Studio is being reviewed</h3><p>MtaaMarket will confirm when you can start publishing physical products for Siaya buyers.</p></div>}<div className="workspace-card seller-orders"><div className="card-title"><div><p className="eyebrow">Fulfilment</p><h2>Incoming orders</h2></div><LayoutDashboard /></div>{vendorDashboard.data?.orders.length ? vendorDashboard.data.orders.map(({ order, station }) => <article className="seller-order" key={order.id}><OrderStatus status={order.status} /><h3>{order.orderNumber}</h3><p>MtaaMarket protects buyer contact details.<br />{station?.name ? `Preferred point: ${station.name}` : `Fulfilment: ${order.fulfilmentMethod.replaceAll("_", " ")}`}</p><strong>{formatKes(order.totalAmount)}</strong></article>) : <div className="workspace-empty compact"><Clock3 /><p>Confirmed marketplace orders will appear here with the fulfilment instructions you need.</p></div>}</div></div><div className="workspace-card inventory-workspace"><div className="card-title"><div><p className="eyebrow">Catalog</p><h2>Your listings</h2></div><Plus /></div>{vendorDashboard.data?.products.length ? <div className="inventory-list">{vendorDashboard.data.products.map(({ product, category }) => <div key={product.id}><span className={`listing-status ${product.status}`}>{product.moderationStatus === "visible" ? product.status : product.moderationStatus}</span><strong>{product.title}</strong><p>{category.name} · {formatKes(product.price)} · {product.stockQuantity} in stock</p></div>)}</div> : <div className="workspace-empty compact"><PackageOpen /><p>Your products will appear here after you save a listing.</p></div>}</div></> : null}</section>
    {profile.data?.role === "admin" && <><section className="admin-strip"><ShieldAlert /><div><p className="eyebrow">Administrator view</p><h2>Marketplace signal</h2></div><span>{adminSummary.data?.orderCount || 0} orders</span><span>{adminSummary.data?.openDisputeCount || 0} open disputes</span><span>{adminSummary.data?.notificationCount || 0} unread updates</span></section><AdminOperationsPanel /></>}
  </div>{disputeOrderId && <div className="dispute-overlay" role="dialog" aria-modal="true" aria-labelledby="dispute-title"><form className="dispute-dialog" onSubmit={submitDispute}><button type="button" className="dialog-close" onClick={() => setDisputeOrderId(null)} aria-label="Close dispute dialog"><X size={18} /></button><p className="eyebrow">Escrow protection</p><h2 id="dispute-title">Open an order dispute</h2><p>Escrow remains held while the marketplace team reviews your request.</p><label>Reason<input required minLength={3} maxLength={120} value={disputeReason} onChange={event => setDisputeReason(event.target.value)} placeholder="e.g. Product does not match listing" /></label><label>What happened?<textarea required minLength={10} maxLength={3000} value={disputeDetails} onChange={event => setDisputeDetails(event.target.value)} placeholder="Share enough detail for a fair review." /></label><button className="primary-cta" disabled={openDispute.isPending}>{openDispute.isPending ? "Submitting…" : "Submit dispute"}</button></form></div>}</MarketplaceLayout>;
}
