import { MarketplaceLayout } from "@/components/MarketplaceLayout";
import { formatKes } from "@/components/ProductCard";
import { VendorProductForm } from "@/components/VendorProductForm";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { Bell, CheckCircle2, CircleAlert, Clock3, LayoutDashboard, PackageCheck, PackageOpen, Plus, ShieldAlert, Store, WalletCards, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

function OrderStatus({ status }: { status: string }) {
  const labels: Record<string, string> = { pending_payment: "Awaiting payment", paid_escrow: "Paid · held in escrow", ready_for_pickup: "Ready for pickup", picked_up: "Pickup confirmed", released_vendor: "Completed", disputed: "Dispute open", cancelled: "Cancelled" };
  return <span className={`order-status ${status}`}>{labels[status] || status}</span>;
}

function BecomeVendor({ onReady }: { onReady: () => void }) {
  const mutation = trpc.marketplace.becomeVendor.useMutation({ onSuccess: () => { toast.success("Your seller workspace is ready."); onReady(); }, onError: error => toast.error(error.message) });
  const [storeName, setStoreName] = useState(""); const [storeSlug, setStoreSlug] = useState(""); const [description, setDescription] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); mutation.mutate({ storeName, storeSlug, description: description || undefined }); };
  return <form onSubmit={submit} className="onboarding-card"><div><p className="eyebrow">Start selling</p><h2>Set up your store</h2><p>Use a distinctive store name. Listings remain private until marketplace verification.</p></div><div className="form-grid"><label>Store name<input value={storeName} onChange={event => { setStoreName(event.target.value); setStoreSlug(event.target.value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")); }} required minLength={3} /></label><label>Store link<input value={storeSlug} onChange={event => setStoreSlug(event.target.value)} required pattern="[a-z0-9-]+" /></label><label className="full-span">About your store<textarea value={description} onChange={event => setDescription(event.target.value)} maxLength={1500} placeholder="Tell buyers what you sell." /></label></div><button className="primary-cta" disabled={mutation.isPending}>{mutation.isPending ? "Setting up…" : "Create seller workspace"}<Store size={17} /></button></form>;
}

export default function DashboardPage() {
  const { isAuthenticated, loading } = useAuth();
  const profile = trpc.marketplace.myProfile.useQuery(undefined, { enabled: isAuthenticated });
  const buyerOrders = trpc.marketplace.buyerOrders.useQuery(undefined, { enabled: isAuthenticated });
  const notifications = trpc.marketplace.notifications.useQuery(undefined, { enabled: isAuthenticated });
  const vendorDashboard = trpc.marketplace.vendorDashboard.useQuery(undefined, { enabled: profile.data?.role === "vendor" || profile.data?.role === "admin" });
  const adminSummary = trpc.marketplace.adminSummary.useQuery(undefined, { enabled: profile.data?.role === "admin" });
  const mpesaStatus = trpc.marketplace.mpesaStatus.useQuery();
  const [disputeOrderId, setDisputeOrderId] = useState<number | null>(null);
  const [disputeReason, setDisputeReason] = useState("");
  const [disputeDetails, setDisputeDetails] = useState("");
  const confirmPickup = trpc.marketplace.confirmPickup.useMutation({ onSuccess: () => { toast.success("Pickup confirmation recorded. The dispute window is now open."); buyerOrders.refetch(); notifications.refetch(); }, onError: error => toast.error(error.message) });
  const initiatePayment = trpc.marketplace.initiatePayment.useMutation({ onSuccess: () => { toast.success("Check your phone and approve the M-Pesa prompt."); buyerOrders.refetch(); }, onError: error => toast.error(error.message) });
  const openDispute = trpc.marketplace.openDispute.useMutation({ onSuccess: () => { toast.success("Your dispute is open. Escrow remains held while it is reviewed."); setDisputeOrderId(null); setDisputeReason(""); setDisputeDetails(""); buyerOrders.refetch(); notifications.refetch(); }, onError: error => toast.error(error.message) });

  if (loading) return <MarketplaceLayout><div className="page-loading">Opening your workspace…</div></MarketplaceLayout>;
  if (!isAuthenticated) return <MarketplaceLayout><div className="auth-gate"><WalletCards /><p className="eyebrow">Your marketplace workspace</p><h1>Sign in to manage orders and listings.</h1><p>Keep your pickup details, payment updates, notifications, and seller tools in one place.</p><button className="primary-cta" onClick={startLogin}>Sign in to continue</button></div></MarketplaceLayout>;

  const isVendor = profile.data?.role === "vendor" || profile.data?.role === "admin";
  const submitDispute = (event: FormEvent) => { event.preventDefault(); if (disputeOrderId) openDispute.mutate({ orderId: disputeOrderId, reason: disputeReason, details: disputeDetails }); };
  return <MarketplaceLayout><div className="dashboard-page">
    <div className="dashboard-intro"><div><p className="eyebrow">Marketplace workspace</p><h1>Welcome back, {profile.data?.displayName?.split(" ")[0] || "shopper"}.</h1><p>Follow each order from payment to pickup, without losing the important details.</p></div><Link href="/" className="secondary-cta">Browse market <PackageOpen size={17} /></Link></div>
    <div className="dashboard-tabs"><a href="#orders"><PackageOpen size={16} /> Orders</a><a href="#notifications"><Bell size={16} /> Updates</a><a href="#seller"><Store size={16} /> Seller tools</a></div>
    <div className="dashboard-grid">
      <section id="orders" className="workspace-card orders-workspace"><div className="card-title"><div><p className="eyebrow">Buyer workspace</p><h2>Your orders</h2></div><PackageCheck /></div>{buyerOrders.isLoading ? <p className="muted-copy">Loading your order history…</p> : buyerOrders.data?.length ? <div className="order-list">{buyerOrders.data.map(({ order, station, vendor }) => <article className="order-row" key={order.id}><div><OrderStatus status={order.status} /><h3>{order.orderNumber}</h3><p>{station?.name || "Pickup station pending"}{vendor?.storeName ? ` · ${vendor.storeName}` : ""}</p></div><div><strong>{formatKes(order.totalAmount)}</strong><span>{new Date(order.createdAt).toLocaleDateString("en-KE")}</span></div><div className="order-actions">{order.status === "pending_payment" && <button disabled={!mpesaStatus.data?.configured || initiatePayment.isPending} onClick={() => initiatePayment.mutate({ orderId: order.id, phone: order.paymentPhone || "" })} className="small-cta">{mpesaStatus.data?.configured ? "Pay with M-Pesa" : "M-Pesa setup pending"}</button>}{order.status === "ready_for_pickup" && <button onClick={() => confirmPickup.mutate({ orderId: order.id })} className="small-cta">Confirm pickup</button>}{["paid_escrow", "ready_for_pickup", "picked_up"].includes(order.status) && <button onClick={() => setDisputeOrderId(order.id)} className="small-cta dispute-action"><CircleAlert size={13} /> Open dispute</button>}</div></article>)}</div> : <div className="workspace-empty"><PackageOpen /><h3>No marketplace orders yet.</h3><p>When you check out, payment and pickup updates will appear here.</p><Link href="/" className="text-cta">Browse products</Link></div>}</section>
      <aside id="notifications" className="workspace-card notification-workspace"><div className="card-title"><div><p className="eyebrow">Order updates</p><h2>Notifications</h2></div><Bell /></div>{notifications.data?.length ? <div className="notification-list">{notifications.data.slice(0, 5).map(notification => <div className={notification.isRead ? "notification" : "notification unread"} key={notification.id}><span className={`notification-dot ${notification.type}`} /><div><strong>{notification.title}</strong><p>{notification.body}</p></div></div>)}</div> : <div className="workspace-empty compact"><Bell /><p>Important payment, pickup, delivery, and dispute updates will be shown here.</p></div>}</aside>
    </div>
    <section id="seller" className="seller-workspace">{profile.data?.role === "buyer" ? <BecomeVendor onReady={() => profile.refetch()} /> : isVendor ? <><div className="vendor-workspace-header"><div><p className="eyebrow">Seller workspace</p><h2>{vendorDashboard.data?.vendor?.storeName || "Your seller tools"}</h2><p>New listings save as drafts until your seller profile is verified.</p></div><span className="verification-badge">{vendorDashboard.data?.vendor?.isVerified ? <><CheckCircle2 size={15} /> Verified seller</> : <><Clock3 size={15} /> Verification pending</>}</span></div><div className="seller-grid"><VendorProductForm onCreated={() => vendorDashboard.refetch()} /><div className="workspace-card seller-orders"><div className="card-title"><div><p className="eyebrow">Fulfilment</p><h2>Incoming orders</h2></div><LayoutDashboard /></div>{vendorDashboard.data?.orders.length ? vendorDashboard.data.orders.map(({ order, buyer, station }) => <article className="seller-order" key={order.id}><OrderStatus status={order.status} /><h3>{order.orderNumber}</h3><p>Buyer: {buyer.displayName}<br />Pickup: {station?.name || "Not selected"}</p><strong>{formatKes(order.totalAmount)}</strong></article>) : <div className="workspace-empty compact"><Clock3 /><p>New paid orders will appear here, ready for you to prepare.</p></div>}</div></div><div className="workspace-card inventory-workspace"><div className="card-title"><div><p className="eyebrow">Catalog</p><h2>Your listings</h2></div><Plus /></div>{vendorDashboard.data?.products.length ? <div className="inventory-list">{vendorDashboard.data.products.map(({ product, category }) => <div key={product.id}><span className={`listing-status ${product.status}`}>{product.status}</span><strong>{product.title}</strong><p>{category.name} · {formatKes(product.price)} · {product.stockQuantity} in stock</p></div>)}</div> : <div className="workspace-empty compact"><PackageOpen /><p>Your products will appear here after you save a listing.</p></div>}</div></> : null}</section>
    {profile.data?.role === "admin" && <section className="admin-strip"><ShieldAlert /><div><p className="eyebrow">Administrator view</p><h2>Marketplace signal</h2></div><span>{adminSummary.data?.orderCount || 0} orders</span><span>{adminSummary.data?.openDisputeCount || 0} open disputes</span><span>{adminSummary.data?.notificationCount || 0} unread updates</span></section>}
  </div>{disputeOrderId && <div className="dispute-overlay" role="dialog" aria-modal="true" aria-labelledby="dispute-title"><form className="dispute-dialog" onSubmit={submitDispute}><button type="button" className="dialog-close" onClick={() => setDisputeOrderId(null)} aria-label="Close dispute dialog"><X size={18} /></button><p className="eyebrow">Escrow protection</p><h2 id="dispute-title">Open an order dispute</h2><p>Escrow remains held while the marketplace team reviews your request.</p><label>Reason<input required minLength={3} maxLength={120} value={disputeReason} onChange={event => setDisputeReason(event.target.value)} placeholder="e.g. Product does not match listing" /></label><label>What happened?<textarea required minLength={10} maxLength={3000} value={disputeDetails} onChange={event => setDisputeDetails(event.target.value)} placeholder="Share enough detail for a fair review." /></label><button className="primary-cta" disabled={openDispute.isPending}>{openDispute.isPending ? "Submitting…" : "Submit dispute"}</button></form></div>}</MarketplaceLayout>;
}
