import { MarketplaceLayout } from "@/components/MarketplaceLayout";
import { ProductCard } from "@/components/ProductCard";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, ChevronRight, HandHeart, MapPin, Search, ShieldCheck, Store, Truck, Zap } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

export default function Home() {
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState<string | undefined>();
  const categories = trpc.marketplace.categories.useQuery();
  const products = trpc.marketplace.products.useQuery({ categorySlug: category, search: search || undefined, limit: 24 });
  const productList = useMemo(() => products.data || [], [products.data]);
  return <MarketplaceLayout>
    <section className="hero-section"><div className="hero-container"><div className="hero-copy"><p className="eyebrow">Siaya’s connected local market</p><h1>Shop local.<br /><em>Or let MtaaMarket help.</em></h1><p className="hero-description">A premium market for physical products serving Siaya buyers. Browse approved local sellers as they join, send an item request, or let MtaaMarket organise the next step for you.</p><div className="hero-actions"><a href="#discover" className="primary-cta">Explore the market <ArrowRight size={17} /></a><Link href="/request" className="text-cta">Request an item <ChevronRight size={16} /></Link></div><div className="trust-row"><span><ShieldCheck size={16} /> Platform-managed support</span><span><MapPin size={16} /> Siaya fulfilment choices</span><span><Store size={16} /> Many approved local sellers</span></div></div><div className="hero-art"><div className="hero-orb orb-one" /><div className="hero-orb orb-two" /><div className="hero-card hero-card-main"><span className="hero-card-tag">ASSISTED MARKET</span><div className="hero-card-icon"><HandHeart /></div><p>Need something not listed?</p><strong>Send it to MtaaMarket</strong></div><div className="hero-card hero-card-float"><Zap size={18} fill="currentColor" /><span>Confirmation before payment</span></div><div className="hero-arc" /></div></div></section>
    <section className="market-strip"><div><CheckCircle2 size={18} /> Physical products only</div><div><Truck size={18} /> Fulfilment confirmed by MtaaMarket</div><div><Store size={18} /> Sellers serve Siaya buyers</div></section>
    <section id="discover" className="discover-section"><div className="section-heading"><div><p className="eyebrow">Browse with confidence</p><h2>The Siaya market, in one place</h2></div><p>Search approved listings or use the Request Desk when you cannot find what you need.</p></div><div className="search-panel"><Search size={19} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search physical products, livestock, accessories, home items and more" aria-label="Search products" /><button onClick={() => { setSearch(""); setCategory(undefined); }}>Reset</button></div><div className="category-row"><button onClick={() => setCategory(undefined)} className={!category ? "category-chip selected" : "category-chip"}>All products</button>{categories.data?.map(item => <button key={item.id} onClick={() => setCategory(item.slug)} className={category === item.slug ? "category-chip selected" : "category-chip"}>{item.name}</button>)}</div>{category === "poultry-livestock" ? <aside className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4 text-sm text-amber-950"><strong>Local poultry & livestock: </strong>every listing needs owner review, original photos, welfare confirmation, and manual collection checks. Request MtaaMarket to confirm availability and the next safe step.</aside> : null}<div className="product-grid">{products.isLoading ? Array.from({ length: 8 }).map((_, index) => <div className="product-skeleton" key={index} />) : productList.length ? productList.map((entry: { product: { id: string | number } }) => <ProductCard key={entry.product.id} entry={entry as any} />) : <div className="empty-discovery"><HandHeart size={28} /><h3>The market is preparing its first verified listings.</h3><p>Tell MtaaMarket what you need and we will begin with your request.</p><Link href="/request" className="text-cta">Open Request Desk <ArrowRight size={15} /></Link></div>}</div></section>
    <section className="how-section"><div className="how-visual"><div className="how-stamp">SM</div><p>For people who shop online and people who prefer personal help.</p></div><div className="how-copy"><p className="eyebrow">More than a catalogue</p><h2>A local market that works around real life.</h2><div className="steps"><div><span>01</span><p><strong>Browse or ask</strong>Shop approved physical products, or describe the item you need in the Request Desk.</p></div><div><span>02</span><p><strong>MtaaMarket confirms</strong>The platform confirms availability, fulfilment choices, and the right payment instruction before anything is collected.</p></div><div><span>03</span><p><strong>Receive with clarity</strong>Choose a Siaya pickup, home-delivery, or collection-point preference and follow the update in your workspace.</p></div></div><Link href="/request" className="secondary-cta">Ask MtaaMarket for an item <ArrowRight size={17} /></Link></div></section>
  </MarketplaceLayout>;
}
