import { MarketplaceLayout } from "@/components/MarketplaceLayout";
import { PickupMap } from "@/components/PickupMap";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Clock3, ExternalLink, HandHeart, MapPin, Navigation, Phone, Store } from "lucide-react";
import { Link } from "wouter";

type PublicStation = { id: string | number; county: string; name: string; town: string; address: string; landmark: string | null; openingHours: string | null; contactPhone: string | null; latitude: number | null; longitude: number | null };

export default function PickupStations() {
  const stations = trpc.marketplace.pickupStations.useQuery();
  const stationList = (stations.data || []) as PublicStation[];
  return <MarketplaceLayout><div className="stations-page"><div className="station-hero"><p className="eyebrow">Fulfilment made clear</p><h1>Choose the Siaya option that suits you.</h1><p>MtaaMarket confirms available pickup, collection-point, and home-delivery options after reviewing your order. We only publish a location after its details are verified.</p></div><div className="station-directory-header"><div><h2>Verified public collection points</h2><p>Use the Request Desk if you want to suggest a known point or need MtaaMarket to advise.</p></div><div className="map-coming"><Navigation size={18} /> Map appears when verified points are available</div></div>{stationList.length ? <><section className="map-section"><PickupMap stations={stationList as any} /></section><div className="station-grid">{stationList.map(station => { const directions = `https://www.google.com/maps/dir/?api=1&destination=${station.latitude},${station.longitude}`; return <article className="station-card" key={station.id}><div className="station-pin"><MapPin /></div><div><p className="product-category">{station.county}</p><h2>{station.name}</h2><p className="station-town">{station.town}</p></div><div className="station-details"><p><Store size={16} /> {station.address}</p>{station.landmark && <p><Navigation size={16} /> {station.landmark}</p>}{station.openingHours && <p><Clock3 size={16} /> {station.openingHours}</p>}{station.contactPhone && <p><Phone size={16} /> {station.contactPhone}</p>}</div><a href={directions} target="_blank" rel="noreferrer" className="station-directions">Open directions <ExternalLink size={15} /></a></article>; })}</div></> : stations.isLoading ? <div className="page-loading">Checking available collection points…</div> : <div className="empty-discovery"><HandHeart size={28} /><h3>MtaaMarket is verifying the first Siaya collection points.</h3><p>For now, choose a fulfilment preference in your order request and the platform will confirm a safe available route.</p><Link href="/request" className="text-cta">Suggest a point or request an item <ArrowRight size={15} /></Link></div>}</div></MarketplaceLayout>;
}
