import { MarketplaceLayout } from "@/components/MarketplaceLayout";
import { PickupMap } from "@/components/PickupMap";
import { trpc } from "@/lib/trpc";
import { Clock3, ExternalLink, MapPin, Navigation, Phone, Store } from "lucide-react";

export default function PickupStations() {
  const stations = trpc.marketplace.pickupStations.useQuery();
  return <MarketplaceLayout><div className="stations-page"><div className="station-hero"><p className="eyebrow">Collection made clear</p><h1>Pickup stations that fit your route.</h1><p>Choose a station at checkout, receive order updates, and collect when your order is ready.</p></div><div className="station-directory-header"><div><h2>Station directory</h2><p>Addresses, landmarks and opening times are shown before you pay.</p></div><div className="map-coming"><Navigation size={18} /> View every station on the interactive map</div></div>{stations.data?.length ? <section className="map-section"><PickupMap stations={stations.data} /></section> : null}<div className="station-grid">{stations.isLoading ? <div className="page-loading">Loading stations…</div> : stations.data?.map(station => { const directions = `https://www.google.com/maps/dir/?api=1&destination=${station.latitude},${station.longitude}`; return <article className="station-card" key={station.id}><div className="station-pin"><MapPin /></div><div><p className="product-category">{station.county}</p><h2>{station.name}</h2><p className="station-town">{station.town}</p></div><div className="station-details"><p><Store size={16} /> {station.address}</p>{station.landmark && <p><Navigation size={16} /> {station.landmark}</p>}{station.openingHours && <p><Clock3 size={16} /> {station.openingHours}</p>}{station.contactPhone && <p><Phone size={16} /> {station.contactPhone}</p>}</div><a href={directions} target="_blank" rel="noreferrer" className="station-directions">Open directions <ExternalLink size={15} /></a></article>; })}</div></div></MarketplaceLayout>;
}
