import { MarketplaceLayout } from "@/components/MarketplaceLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { BadgeCheck, BarChart3, Boxes, CheckCircle2, ChevronRight, ShieldCheck, Store } from "lucide-react";
import { useLocation } from "wouter";

export default function VendorPage() {
  const { isAuthenticated } = useAuth();
  const [, setLocation] = useLocation();
  return <MarketplaceLayout><div className="vendor-page"><section className="vendor-hero"><div><p className="eyebrow">Siaya Online MtaaMarket Seller Studio</p><h1>Sell to Siaya.<br />Stay in control.</h1><p>Apply once, then publish physical-product listings when MtaaMarket approves your Seller Studio. The platform keeps buyer contact private and manages the customer-facing order journey.</p><button className="primary-cta" onClick={() => isAuthenticated ? setLocation("/dashboard") : startLogin()}>{isAuthenticated ? "Open Seller Studio" : "Apply to sell"} <ChevronRight size={17} /></button></div><div className="vendor-illustration"><div><Store size={30} /><span>SELLER STUDIO</span><strong>Built to serve Siaya</strong></div><div className="vendor-stat"><BarChart3 size={19} /> Order visibility</div><div className="vendor-stat lower"><Boxes size={19} /> Original listings</div></div></section><section className="seller-benefits"><article><BadgeCheck /><h2>Sell after approval</h2><p>Once your Seller Studio is approved, you can publish physical-product listings immediately. MtaaMarket can pause or remove listings that break the marketplace rules.</p></article><article><ShieldCheck /><h2>Keep contact protected</h2><p>MtaaMarket keeps buyer information private and sends you only the fulfilment instruction needed to prepare an order.</p></article><article><CheckCircle2 /><h2>Serve Siaya reliably</h2><p>Vendors can be based in Siaya or elsewhere, provided they can reliably fulfil orders for Siaya buyers.</p></article></section><section className="vendor-callout"><p className="eyebrow">Listing quality matters</p><h2>Use original photos, clear details, and the right availability information.</h2><p>Your photos are compressed in the browser before secure upload. Seller Studio will also guide you on condition, payment timing, and available fulfilment preferences without showing private buyer details.</p></section></div></MarketplaceLayout>;
}
