import { trpc } from "@/lib/trpc";
import { ImagePlus, Loader2, PackagePlus } from "lucide-react";
import { ChangeEvent, FormEvent, useState } from "react";
import { toast } from "sonner";

async function compressToWebp(file: File) {
  if (!file.type.startsWith("image/")) throw new Error("Choose an image file.");
  if (file.size > 12 * 1024 * 1024) throw new Error("Choose an image smaller than 12 MB.");
  const source = await createImageBitmap(file); const largestEdge = 1600; const scale = Math.min(1, largestEdge / Math.max(source.width, source.height));
  const canvas = document.createElement("canvas"); canvas.width = Math.max(1, Math.round(source.width * scale)); canvas.height = Math.max(1, Math.round(source.height * scale));
  const context = canvas.getContext("2d"); if (!context) throw new Error("Image compression is not available in this browser."); context.drawImage(source, 0, 0, canvas.width, canvas.height); source.close();
  const result = canvas.toDataURL("image/webp", 0.78); if (result.length > 2_700_000) throw new Error("Please choose a smaller image; the compressed upload must be under 2 MB."); return result;
}

export function VendorProductForm({ onCreated }: { onCreated: () => void }) {
  const categories = trpc.marketplace.categories.useQuery(); const createProduct = trpc.marketplace.createVendorProduct.useMutation({ onSuccess: () => { toast.success("Listing saved. It will become public after vendor verification."); onCreated(); }, onError: error => toast.error(error.message) });
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [categoryId, setCategoryId] = useState(""); const [price, setPrice] = useState(""); const [stockQuantity, setStockQuantity] = useState("1"); const [imageDataUrl, setImageDataUrl] = useState<string>(); const [imageName, setImageName] = useState(""); const [compressing, setCompressing] = useState(false);
  const selectImage = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setCompressing(true); try { setImageDataUrl(await compressToWebp(file)); setImageName(`${file.name.replace(/\.[^.]+$/, "")}.webp`); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not prepare the image."); event.target.value = ""; } finally { setCompressing(false); } };
  const submit = (event: FormEvent) => { event.preventDefault(); createProduct.mutate({ title, description, categoryId: Number(categoryId), price: Number(price), stockQuantity: Number(stockQuantity), imageDataUrl }); };
  return <form onSubmit={submit} className="listing-form"><div className="form-heading"><div><p className="eyebrow">New listing</p><h2>Add a product</h2></div><PackagePlus /></div><div className="form-grid"><label>Product title<input required minLength={4} maxLength={180} value={title} onChange={event => setTitle(event.target.value)} placeholder="e.g. Handwoven everyday tote" /></label><label>Category<select required value={categoryId} onChange={event => setCategoryId(event.target.value)}><option value="">Select category</option>{categories.data?.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="full-span">Description<textarea required minLength={20} maxLength={5000} value={description} onChange={event => setDescription(event.target.value)} placeholder="Describe the product, its condition, and what the buyer will receive." /></label><label>Price (KES)<input required type="number" min="1" step="1" value={price} onChange={event => setPrice(event.target.value)} placeholder="0" /></label><label>Stock quantity<input required type="number" min="0" max="100000" value={stockQuantity} onChange={event => setStockQuantity(event.target.value)} /></label></div><label className="image-uploader"><input type="file" accept="image/*" onChange={selectImage} /><ImagePlus size={20} /><span>{compressing ? "Compressing to WebP…" : imageName || "Add a product image"}</span><small>Optional · compressed in your browser before secure upload</small></label><button disabled={createProduct.isPending || compressing} className="primary-cta form-submit">{createProduct.isPending ? <Loader2 className="animate-spin" size={17} /> : <PackagePlus size={17} />}{createProduct.isPending ? "Saving listing…" : "Save listing"}</button></form>;
}
